# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-06 04:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180206_0406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='c_order',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Order'),
        ),
    ]
