# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-07 02:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180206_0406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='o_create_time',
            field=models.DateTimeField(auto_created=True, auto_now=True),
        ),
    ]
